### ISSUE TITLE
上传分片至FastDfs耗时过多如何解决

### ISSUE THREAD

**Issue by FanGogh** [ykrenz/springboot-file-server#9]
您好，作者，能向你请教下最后合并分片的时候，merge接口很慢的问题如何解决？

**Comment by renxiaokui** [comment]
你好 fdfs实质是使用断点续传处理 多线程分片上传 最后合并 耗时是难免的

如果真的想解决该问题 可以考虑使用单线程上传分片 追加方式直接上传到fdfs中 也就是断点续传

现在代码还在重构中 可持续关注下代码情况

**Comment by FanGogh** [comment]
好的，一直在持续关注，感谢解惑答疑，不知道您后面会不会加上关于Minio的支持呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "renxiaokui/springboot-file-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [renxiaokui/springboot-file-server] 上传分片至FastDfs耗时过多如何解决 (#9)





 
你好 fdfs实质是使用断点续传处理 多线程分片上传 最后合并 耗时是难免的
 
如果真的想解决该问题 可以考虑使用单线程上传分片 追加方式直接上传到fdfs中 也就是断点续传
 
现在代码还在重构中 可持续关注下代码情况

**Comment by renxiaokui** [comment]
感谢支持。会的，这个是在计划之中

**Comment by FanGogh** [comment]
感谢
